### ISSUE TITLE
(SC006) 본인 게시물 아니어도 수정, 삭제 가능한 현상

### ISSUE THREAD

**Issue by yoon38943** [daedongyourjido/full_code#28]
### 1. 개요

- 본인의 게시물이 아니어도 게시물의 수정, 삭제가 가능한 현상 발생
![image](https://github.com/daedongyourjido/full_code/assets/125805074/4b909759-c3e5-40ae-85ed-2b44bc30c968)
![image](https://github.com/daedongyourjido/full_code/assets/125805074/115d4a5b-a0aa-422d-a9c0-3e1c83f2b381)

- 로그아웃 상황에서도 발생
- 결함 발생 시나리오
`1. 서버에 배포된 대동유어지도 웹 사이트(dyz.co.kr)에 입장함`
`2. 로그인 or 로그아웃 상태로 게시물 페이지 입장함`
`3. 아무 게시물이나 클릭 후 수정 혹은 삭제`

**Comment by bear-frog** [comment]
### 2. 수정

* 쿼리스트링 값이 세션id와 일치할 경우에만 해당 ui 도출하도록 함
```html
{/*쿼리스트링 값이 세션스토리지 id와 일치할 경우에만 수정 ui 도출*/}
{queryParams.get('user') === sessionStorage.id ? <>
    <SettingsIcon
        sx={{color:'black', marginTop:'1.4vh', marginLeft:'6vw', cursor:'pointer'}}
        onClick={() => {
            navigate(`/write?locationid=${props.info.id}`);
        }}/>
    <DeleteIcon
        sx={{color:'black', marginTop:'1.4vh', cursor:'pointer'}}
        onClick={handleDelete}
    /></> : <></>}
```

### 3. 수정 후 정상 동작 확인

* 마이페이지
![image](https://github.com/daedongyourjido/full_code/assets/66404645/cc3ae4cb-876d-438f-8fdc-882ee73d0558)

* 지역 페이지
![image](https://github.com/daedongyourjido/full_code/assets/66404645/e1aabe2c-4107-461b-a50a-05dc98f0730d)
