### ISSUE TITLE
(SC006) 다른 사람이 올린 게시물도 로그인한 본인의 프로필로 보이는 현상 발생

### ISSUE THREAD

**Issue by yoon38943** [daedongyourjido/full_code#33]
### 1. 개요

- 로그인 후 게시물을 확인하면 게시물의 작성자가 본인의 프로필로 표기되는 현상 발생
![image](https://github.com/daedongyourjido/full_code/assets/125805074/56bbf748-3e94-44e2-b457-b9d7bfa92155)
![image](https://github.com/daedongyourjido/full_code/assets/125805074/4bf66bec-33b1-4a65-bbed-2c4a6baf6fd8)

- 로그아웃 시에는 프로필이 표기되지 않음
- 결함 발생 시나리오
`1. 로그인 or 로그아웃 상태로 게시물 페이지 입장`
`2. 아무 게시물 열람`
`3. 게시물의 작성자가 본인 or 로그아웃 상태로 표기됨`

**Comment by bear-frog** [comment]
### 2. 수정

* 코드 수정했어요 이제 잘 보임(버그는 난몰라)
