### ISSUE TITLE
(SC009) 프로필 사진 등록 시 높은 확률로 프로필에 바로 반영이 안 되는 현상

### ISSUE THREAD

**Issue by yoon38943** [daedongyourjido/full_code#35]
### 1. 개요

- 프로필 페이지에서 새로운 프로필 사진을 등록할 때 높은 확률로 사진이 바로 반영되지 않음
![image](https://github.com/daedongyourjido/full_code/assets/125805074/89bc8e23-833d-44a8-b358-e9721cdc5efc)

- 프로필 페이지에서 사진을 바꿔도 헤더의 프로필이 바로 반영되지 않음
- 페이지 이동 등의 방법을 사용해도 바뀌지 않은 프로필이 유지됨
- 로그아웃 후 새롭게 로그인 하면 바뀐 프로필이 반영이 되어있음

- 결함 발생 시나리오
`1. 로그인 후에 프로필 페이지 진입`
`2. 프로필 페이지에서 프로필 사진을 변경 => 결함 발생`

**Comment by bear-frog** [comment]
### 2. 수정

* 이미지 업로드 시 페이지 새로고침으로 바꿨어요
    * useEffect 등으로 변경 감지하도록 추후 바꿔도 괜찮을듯
